/* FPL Daily Challenge calendar manifest.
   Generated by Challenge Studio Seven-Day Calendar.
   Upload dated challenge files first, then replace this manifest last. */
window.FPL_CHALLENGE_MANIFEST = {
  "version": 4,
  "timezone": "Europe/London",
  "fallbackPath": "todays-challenge.js",
  "rotationPolicy": {
    "version": 1,
    "exactPromptRotation": "full-compatible-position-cycle",
    "familyCooldownDays": 7,
    "familyScope": "position-scoped-template-family",
    "familyFallback": "relax-family-only-when-required"
  },
  "challenges": [
    {
      "date": "2026-08-06",
      "path": "challenges/2026-08-06.js",
      "id": "daily-008-the-generated-mix",
      "number": 8,
      "title": "6 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1797,
      "promptIds": [],
      "promptFamilies": [],
      "familyCooldownRelaxedPositions": []
    },
    {
      "date": "2026-08-10",
      "path": "challenges/2026-08-10.js",
      "id": "daily-030-the-generated-mix",
      "number": 30,
      "title": "10 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1988,
      "promptIds": [
        "auto_gk_clean_12_price_5_5",
        "auto_def_goals_4_minutes_1500",
        "auto_def_teammate_marc_guehi",
        "def_zero_goals_5assists",
        "auto_def_frank_lampard_minutes_1000_excluding_ben_chilwell_cesar_azpilicueta",
        "auto_mid_teammate_troy_deeney",
        "auto_mid_goals_4_league_13_17",
        "auto_mid_teammate_harry_maguire_points_80",
        "mid_longname_120",
        "auto_fwd_teammate_declan_rice",
        "auto_fwd_teammate_jordan_pickford"
      ],
      "promptFamilies": [],
      "familyCooldownRelaxedPositions": []
    },
    {
      "date": "2026-08-11",
      "path": "challenges/2026-08-11.js",
      "id": "daily-2026-08-11-the-generated-mix",
      "number": 37,
      "title": "11 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 2145,
      "promptIds": [
        "auto_gk_season_2014_15_points_40",
        "auto_def_after_2022_23_points_90",
        "auto_def_teammate_ross_barkley_points_70",
        "auto_def_returned_to_former_club",
        "auto_def_career_seasons_exact_8_minutes_2000",
        "mid_surname_d_100",
        "auto_mid_relegated_gi_8",
        "auto_mid_frank_lampard_minutes_1000",
        "mid_10_clean_5involvements_bottomhalf",
        "auto_fwd_career_clubs_3_points_60",
        "fwd_midtable_10goals"
      ],
      "promptFamilies": [
        "GK:season:season-exact",
        "DEF:season:season-after",
        "DEF:teammate+points",
        "DEF:career:career-clubs",
        "DEF:career:career-seasons",
        "MID:name:surname",
        "MID:goal-involvements+relegated",
        "MID:manager+minutes",
        "MID:clean-sheets+goal-involvements",
        "FWD:career:career-clubs",
        "FWD:goals+mid-table"
      ],
      "familyCooldownRelaxedPositions": []
    },
    {
      "date": "2026-08-12",
      "path": "challenges/2026-08-12.js",
      "id": "daily-2026-08-12-the-generated-mix",
      "number": 38,
      "title": "12 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 2066,
      "promptIds": [
        "auto_gk_saves_70_league_10_15_excluding_emiliano_martinez_nick_pope",
        "auto_def_surname_r_minutes_excluding_andrew_robertson_antonio_rudiger",
        "def_13_17_2500",
        "auto_def_season_2017_18_points_110",
        "auto_def_points_150_210",
        "auto_mid_assists_over_goals_12",
        "mid_budget_involvements",
        "mid_promoted_5assists",
        "auto_mid_returned_to_former_club",
        "auto_fwd_season_2018_19_points_70",
        "auto_fwd_relegated_goals_6"
      ],
      "promptFamilies": [
        "GK:league-position+saves",
        "DEF:name:surname",
        "DEF:minutes+survival",
        "DEF:season:season-exact",
        "DEF:points",
        "MID:assists",
        "MID:budget+goal-involvements",
        "MID:assists+promoted",
        "MID:career:career-clubs",
        "FWD:season:season-exact",
        "FWD:goals+relegated"
      ],
      "familyCooldownRelaxedPositions": []
    },
    {
      "date": "2026-08-13",
      "path": "challenges/2026-08-13.js",
      "id": "daily-2026-08-13-the-generated-mix",
      "number": 39,
      "title": "13 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 2262,
      "promptIds": [
        "auto_gk_before_2015_16_points_80_excluding_tim_howard_joe_hart",
        "auto_def_clean_12_price_4_5",
        "def_survival_4assists",
        "auto_def_same_initials_points_excluding_virgil_van_dijk_conor_coady",
        "def_100pts_6yellows",
        "auto_mid_same_initials_points",
        "auto_mid_promoted_gi_10",
        "auto_mid_goals_10_assists_7",
        "mid_age30_120",
        "auto_fwd_league_5_8_1800",
        "auto_fwd_career_seasons_6_points_60_excluding_harry_kane"
      ],
      "promptFamilies": [
        "GK:season:season-before",
        "DEF:budget+clean-sheets",
        "DEF:assists+survival",
        "DEF:name:initials",
        "DEF:cards+points",
        "MID:name:initials",
        "MID:goal-involvements+promoted",
        "MID:assists+goals",
        "MID:age+points",
        "FWD:league-position+minutes",
        "FWD:career:career-seasons"
      ],
      "familyCooldownRelaxedPositions": []
    },
    {
      "date": "2026-08-14",
      "path": "challenges/2026-08-14.js",
      "id": "daily-2026-08-14-the-generated-mix",
      "number": 40,
      "title": "14 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 2132,
      "promptIds": [
        "auto_gk_promoted_saves_90",
        "def_onegoal_10cs",
        "def_promoted_80_points",
        "def_relegated_5cs",
        "def_top4_5assists",
        "mid_relegated_100points",
        "mid_sean_dyche_5involvements",
        "auto_mid_career_seasons_exact_8_minutes_2000_excluding_sadio_mane",
        "auto_mid_points_150_210",
        "auto_fwd_age_31_35_1400",
        "auto_fwd_surname_length_8"
      ],
      "promptFamilies": [
        "GK:promoted+saves",
        "DEF:clean-sheets+goals",
        "DEF:points+promoted",
        "DEF:clean-sheets+relegated",
        "DEF:assists+top-four",
        "MID:points+relegated",
        "MID:manager+goal-involvements",
        "MID:career:career-seasons",
        "MID:points",
        "FWD:age+minutes",
        "FWD:name:surname"
      ],
      "familyCooldownRelaxedPositions": []
    },
    {
      "date": "2026-08-15",
      "path": "challenges/2026-08-15.js",
      "id": "daily-2026-08-15-the-generated-mix",
      "number": 41,
      "title": "15 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 2192,
      "promptIds": [
        "gk_surname_m",
        "def_bottom_half_100_points",
        "def_7_12_5assists",
        "def_promoted_2500",
        "def_relegated_3_assists",
        "auto_mid_season_2012_13_points_130_excluding_gareth_bale_juan_mata",
        "auto_mid_hyphenated_minutes",
        "mid_top4_15gi",
        "auto_mid_age_31_35_1400",
        "fwd_13_17_10goals",
        "auto_fwd_bottomhalf_goals_10"
      ],
      "promptFamilies": [
        "GK:name:surname",
        "DEF:bottom-half+points",
        "DEF:assists+mid-table",
        "DEF:minutes+promoted",
        "DEF:assists+relegated",
        "MID:season:season-exact",
        "MID:name:hyphenated",
        "MID:goal-involvements+top-four",
        "MID:age+minutes",
        "FWD:goals+survival",
        "FWD:bottomhalf+goals"
      ],
      "familyCooldownRelaxedPositions": []
    },
    {
      "date": "2026-08-16",
      "path": "challenges/2026-08-16.js",
      "id": "daily-2026-08-16-the-generated-mix",
      "number": 42,
      "title": "16 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1895,
      "promptIds": [
        "auto_gk_between_2012_13_2016_17_points_80_excluding_tim_howard_petr_cech",
        "def_start_40_1500",
        "def_2500_5bonus_zero_goal",
        "auto_def_first_r_points_excluding_ricardo_barbosa_pereira",
        "auto_def_bottom_assists_3",
        "mid_survival_9gi",
        "mid_final5_100",
        "mid_10yellows_100",
        "mid_promoted_100",
        "auto_fwd_outside_goals_12",
        "auto_fwd_teammate_declan_rice_points_70"
      ],
      "promptFamilies": [
        "GK:season:season-between",
        "DEF:budget+minutes",
        "DEF:bonus+minutes",
        "DEF:name:first-name",
        "DEF:assists+bottom-half",
        "MID:goal-involvements+survival",
        "MID:budget+points",
        "MID:cards+points",
        "MID:points+promoted",
        "FWD:goals",
        "FWD:teammate+points"
      ],
      "familyCooldownRelaxedPositions": []
    },
    {
      "date": "2026-08-17",
      "path": "challenges/2026-08-17.js",
      "id": "daily-2026-08-17-the-generated-mix",
      "number": 43,
      "title": "17 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 2179,
      "promptIds": [
        "auto_gk_career_clubs_exact_1_minutes_1800_excluding_alisson_becker",
        "def_outside_big6_gc30_2000",
        "def_longname_100points",
        "def_exact_3_goals_midtable",
        "def_10yellows_2000",
        "mid_bottomhalf_3000_no_red",
        "mid_bottomhalf_10_goals",
        "auto_mid_first_a_points_excluding_alexis_sanchez",
        "mid_2500_10bonus_astgtgoal",
        "auto_fwd_between_2021_22_2025_26_points_85",
        "auto_fwd_gi_15_price_6_5"
      ],
      "promptFamilies": [
        "GK:career:career-clubs",
        "DEF:minutes",
        "DEF:name:name-length",
        "DEF:goals+mid-table",
        "DEF:cards+minutes",
        "MID:discipline+minutes",
        "MID:bottom-half+goals",
        "MID:name:first-name",
        "MID:assists+minutes",
        "FWD:season:season-between",
        "FWD:budget+goal-involvements"
      ],
      "familyCooldownRelaxedPositions": []
    }
  ]
};
