/* FPL Daily Challenge calendar manifest.
   Generated by Challenge Studio Seven-Day Calendar.
   Upload dated challenge files first, then replace this manifest last. */
window.FPL_CHALLENGE_MANIFEST = {
  "version": 2,
  "timezone": "Europe/London",
  "fallbackPath": "todays-challenge.js",
  "challenges": [
    {
      "date": "2026-08-06",
      "path": "challenges/2026-08-06.js",
      "id": "daily-008-the-generated-mix",
      "number": 8,
      "title": "Challenge #8 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1797,
      "promptIds": []
    },
    {
      "date": "2026-08-11",
      "path": "challenges/2026-08-11.js",
      "id": "daily-016-the-generated-mix",
      "number": 16,
      "title": "Challenge #16 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1854,
      "promptIds": [
        "gk_exact_10_cs_outside_big_six",
        "auto_def_teammate_nick_pope_excluding_kieran_trippier",
        "auto_def_alan_pardew_minutes_1000",
        "auto_def_teammate_james_milner_points_70_excluding_andrew_robertson",
        "auto_def_surname_h_minutes_excluding_robert_huth",
        "auto_mid_goals_6_league_7_12",
        "auto_mid_teammate_cheikhou_kouyate_points_80",
        "auto_mid_before_2015_16_points_100",
        "auto_mid_teammate_danny_welbeck_points_80_excluding_alexis_sanchez",
        "auto_fwd_teammate_jacob_murphy_excluding_alexander_isak",
        "auto_fwd_surname_d_minutes_excluding_matheus_santos_carneiro_da_cunha_joao_pe"
      ]
    },
    {
      "date": "2026-08-12",
      "path": "challenges/2026-08-12.js",
      "id": "daily-017-the-generated-mix",
      "number": 17,
      "title": "Challenge #17 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1826,
      "promptIds": [
        "auto_gk_season_2022_23_points_70",
        "auto_def_teammate_douglas_luiz_soares_de_paulo",
        "auto_def_teammate_cesar_azpilicueta_excluding_branislav_ivanovic",
        "auto_def_mark_hughes_minutes_1000",
        "def_surname_t_1000",
        "mid_exact_7_goals_7_12",
        "auto_mid_teammate_dominic_calvert_lewin_excluding_gylfi_sigurdsson",
        "auto_mid_teammate_jean_philippe_mateta",
        "auto_mid_teammate_callum_wilson_points_80_excluding_anthony_gordon",
        "auto_fwd_teammate_danny_welbeck",
        "auto_fwd_teammate_alex_iwobi_excluding_pierre_emerick_aubameyang_alexandre_la"
      ]
    },
    {
      "date": "2026-08-13",
      "path": "challenges/2026-08-13.js",
      "id": "daily-018-the-generated-mix",
      "number": 18,
      "title": "Challenge #18 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 2037,
      "promptIds": [
        "auto_gk_season_2025_26_points_70_excluding_david_raya_martin",
        "auto_def_teammate_wilfried_zaha",
        "auto_def_teammate_james_maddison_excluding_ricardo_barbosa_pereira",
        "auto_def_nuno_espirito_santo_minutes_1000",
        "auto_def_teammate_erik_pieters",
        "auto_mid_assists_over_goals_12",
        "auto_mid_goals_12_assists_7_excluding_mohamed_salah",
        "auto_mid_brendan_rodgers_minutes_1000_excluding_james_maddison",
        "auto_mid_teammate_lukasz_fabianski_points_80_excluding_jarrod_bowen_gylfi_sig",
        "auto_fwd_teammate_riyad_mahrez",
        "auto_fwd_teammate_cheikhou_kouyate"
      ]
    },
    {
      "date": "2026-08-14",
      "path": "challenges/2026-08-14.js",
      "id": "daily-019-the-generated-mix",
      "number": 19,
      "title": "Challenge #19 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1818,
      "promptIds": [
        "auto_gk_relegated_saves_70",
        "auto_def_teammate_victor_lindelof_excluding_antonio_valencia_aaron_wan_bissak",
        "auto_def_brendan_rodgers_minutes_1000_excluding_ricardo_barbosa_pereira",
        "auto_def_first_r_points_excluding_ricardo_barbosa_pereira",
        "auto_def_season_2017_18_points_110",
        "mid_surname_10letters_100",
        "auto_mid_teammate_wilfried_zaha_excluding_luka_milivojevic",
        "auto_mid_teammate_adama_traore_points_80_excluding_alex_iwobi",
        "auto_mid_teammate_alex_iwobi_points_80_excluding_alexis_sanchez",
        "auto_fwd_teammate_nathaniel_clyne",
        "auto_fwd_teammate_anthony_gordon"
      ]
    },
    {
      "date": "2026-08-15",
      "path": "challenges/2026-08-15.js",
      "id": "daily-020-the-generated-mix",
      "number": 20,
      "title": "Challenge #20 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1886,
      "promptIds": [
        "auto_gk_promoted_saves_110",
        "auto_def_teammate_marc_guehi",
        "auto_def_teammate_lucas_digne",
        "auto_def_teammate_granit_xhaka",
        "auto_def_career_seasons_exact_6_minutes_2000",
        "auto_mid_sam_allardyce_minutes_1800",
        "auto_mid_season_2024_25_points_130_excluding_mohamed_salah_bryan_mbeumo",
        "auto_mid_marco_silva_minutes_1000",
        "auto_mid_teammate_marcos_alonso_excluding_eden_hazard_mason_mount",
        "auto_fwd_season_2021_22_points_40",
        "auto_fwd_teammate_ryan_fraser_excluding_callum_wilson"
      ]
    },
    {
      "date": "2026-08-16",
      "path": "challenges/2026-08-16.js",
      "id": "daily-021-the-generated-mix",
      "number": 21,
      "title": "Challenge #21 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1841,
      "promptIds": [
        "auto_gk_age_23_27_2000",
        "auto_def_teammate_troy_deeney",
        "auto_def_dean_smith_minutes_1000_excluding_matty_cash",
        "auto_def_season_2022_23_points_110_excluding_kieran_trippier",
        "auto_def_teammate_jordan_ayew_points_70_excluding_patrick_van_aanholt",
        "auto_mid_goals_6_league_10_15",
        "auto_mid_season_2023_24_points_130",
        "auto_mid_teammate_jordan_henderson_points_80_excluding_mohamed_salah_sadio_ma",
        "auto_mid_teammate_jack_cork_points_80_excluding_gylfi_sigurdsson_adam_lallana",
        "auto_fwd_teammate_dean_henderson",
        "auto_fwd_career_seasons_8_10_points_60"
      ]
    },
    {
      "date": "2026-08-17",
      "path": "challenges/2026-08-17.js",
      "id": "daily-022-the-generated-mix",
      "number": 22,
      "title": "Challenge #22 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 2125,
      "promptIds": [
        "auto_gk_season_2019_20_points_40",
        "auto_def_career_clubs_3_points_60",
        "auto_def_bottom_assists_5",
        "auto_def_teammate_ayoze_perez_excluding_jonny_evans",
        "auto_def_teammate_tyrone_mings",
        "auto_mid_teammate_harry_maguire_points_80",
        "auto_mid_jurgen_klopp_minutes_1000_excluding_mohamed_salah",
        "auto_mid_teammate_tomas_soucek_excluding_jarrod_bowen",
        "auto_mid_career_seasons_10_points_70",
        "auto_fwd_season_2024_25_points_70_excluding_alexander_isak_chris_wood",
        "auto_fwd_promoted_goals_8"
      ]
    }
  ]
};
