/* FPL Daily Challenge calendar manifest.
   Generated by Challenge Studio Seven-Day Calendar.
   Upload dated challenge files first, then replace this manifest last. */
window.FPL_CHALLENGE_MANIFEST = {
  "version": 3,
  "timezone": "Europe/London",
  "fallbackPath": "todays-challenge.js",
  "challenges": [
    {
      "date": "2026-08-06",
      "path": "challenges/2026-08-06.js",
      "id": "daily-008-the-generated-mix",
      "number": 8,
      "title": "6 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1797,
      "promptIds": []
    },
    {
      "date": "2026-08-10",
      "path": "challenges/2026-08-10.js",
      "id": "daily-030-the-generated-mix",
      "number": 30,
      "title": "10 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1988,
      "promptIds": [
        "auto_gk_clean_12_price_5_5",
        "auto_def_goals_4_minutes_1500",
        "auto_def_teammate_marc_guehi",
        "def_zero_goals_5assists",
        "auto_def_frank_lampard_minutes_1000_excluding_ben_chilwell_cesar_azpilicueta",
        "auto_mid_teammate_troy_deeney",
        "auto_mid_goals_4_league_13_17",
        "auto_mid_teammate_harry_maguire_points_80",
        "mid_longname_120",
        "auto_fwd_teammate_declan_rice",
        "auto_fwd_teammate_jordan_pickford"
      ]
    },
    {
      "date": "2026-08-11",
      "path": "challenges/2026-08-11.js",
      "id": "daily-031-the-generated-mix",
      "number": 31,
      "title": "11 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1756,
      "promptIds": [
        "gk_exact_10_cs_outside_big_six",
        "auto_def_teammate_abdoulaye_doucoure",
        "auto_def_teammate_marcus_rashford",
        "auto_def_teammate_matt_doherty_points_70",
        "auto_def_surname_a_minutes_excluding_trent_alexander_arnold",
        "auto_mid_goals_6_league_10_15",
        "auto_mid_teammate_david_raya_martin_excluding_bukayo_saka_martin_degaard",
        "auto_mid_surname_f_minutes_excluding_bruno_borges_fernandes",
        "auto_mid_teammate_fabian_schar",
        "auto_fwd_teammate_kurt_zouma_excluding_diego_da_silva_costa_tammy_abraham",
        "auto_fwd_teammate_gylfi_sigurdsson_excluding_dominic_calvert_lewin_fernando_l"
      ]
    },
    {
      "date": "2026-08-12",
      "path": "challenges/2026-08-12.js",
      "id": "daily-032-the-generated-mix",
      "number": 32,
      "title": "12 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1936,
      "promptIds": [
        "auto_gk_clean_12_price_5",
        "auto_def_teammate_michael_keane_excluding_james_tarkowski",
        "auto_def_nuno_espirito_santo_minutes_1800_excluding_matt_doherty_nikola_milen",
        "auto_def_teammate_kyle_walker_excluding_joao_cancelo",
        "auto_def_career_clubs_exact_3_minutes_2000",
        "auto_mid_teammate_kieran_trippier_points_80",
        "auto_mid_teammate_mark_noble_points_80_excluding_jarrod_bowen",
        "auto_mid_teammate_nick_pope_excluding_anthony_gordon_jacob_murphy",
        "auto_mid_teammate_jack_cork_points_80_excluding_gylfi_sigurdsson_adam_lallana",
        "auto_fwd_teammate_joshua_king",
        "auto_fwd_teammate_jay_rodriguez"
      ]
    },
    {
      "date": "2026-08-13",
      "path": "challenges/2026-08-13.js",
      "id": "daily-033-the-generated-mix",
      "number": 33,
      "title": "13 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1995,
      "promptIds": [
        "gk_bottomhalf_120_saves",
        "auto_def_teammate_alex_iwobi_excluding_hector_bellerin",
        "auto_def_graham_potter_minutes_1000",
        "auto_def_surname_length_10",
        "auto_def_scott_parker_minutes_1000_excluding_ola_aina",
        "mid_surname_10letters_100",
        "auto_mid_teammate_richarlison_de_andrade_excluding_son_heung_min_gylfi_sigurd",
        "auto_mid_season_2023_24_points_130",
        "auto_mid_teammate_willian_borges_da_silva_points_80_excluding_eden_hazard",
        "auto_fwd_teammate_ross_barkley",
        "auto_fwd_teammate_ben_mee_points_70"
      ]
    },
    {
      "date": "2026-08-14",
      "path": "challenges/2026-08-14.js",
      "id": "daily-034-the-generated-mix",
      "number": 34,
      "title": "14 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1933,
      "promptIds": [
        "auto_gk_relegated_saves_90_excluding_lukasz_fabianski",
        "auto_def_teammate_erik_pieters",
        "auto_def_teammate_leighton_baines_excluding_seamus_coleman",
        "auto_def_season_2022_23_points_110_excluding_kieran_trippier",
        "auto_def_teammate_robert_sanchez",
        "auto_mid_surname_w_minutes_excluding_georginio_wijnaldum_harry_wilson",
        "auto_mid_returned_to_former_club_minutes_1200_excluding_adam_lallana",
        "auto_mid_teammate_richarlison_de_andrade_points_80",
        "auto_mid_teammate_aaron_ramsdale_excluding_bukayo_saka",
        "auto_fwd_teammate_andros_townsend",
        "auto_fwd_season_2018_19_points_40"
      ]
    },
    {
      "date": "2026-08-15",
      "path": "challenges/2026-08-15.js",
      "id": "daily-035-the-generated-mix",
      "number": 35,
      "title": "15 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1964,
      "promptIds": [
        "auto_gk_saves_90_league_13_17",
        "auto_def_teammate_cesar_azpilicueta_excluding_branislav_ivanovic",
        "auto_def_teammate_alex_iwobi_points_70",
        "auto_def_teammate_christian_eriksen_points_70",
        "auto_def_nuno_espirito_santo_minutes_2500",
        "auto_mid_teammate_jean_philippe_mateta",
        "auto_mid_season_2014_15_points_90_excluding_eden_hazard",
        "auto_mid_surname_h_minutes",
        "mid_firstname_j_100",
        "fwd_age_u22_5goals",
        "auto_fwd_teammate_aaron_ramsdale_excluding_gabriel_fernando_de_jesus"
      ]
    },
    {
      "date": "2026-08-16",
      "path": "challenges/2026-08-16.js",
      "id": "daily-036-the-generated-mix",
      "number": 36,
      "title": "16 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 1819,
      "promptIds": [
        "gk_promoted_90_points",
        "auto_def_teammate_ayoze_perez_excluding_jonny_evans",
        "auto_def_teammate_alexis_mac_allister",
        "auto_def_teammate_james_tomkins",
        "auto_def_sam_allardyce_minutes_1800",
        "auto_mid_season_2025_26_points_130",
        "auto_mid_teammate_pierre_emerick_aubameyang_excluding_bukayo_saka",
        "auto_mid_teammate_ryan_bertrand_points_80",
        "auto_mid_teammate_jordan_henderson_points_80_excluding_mohamed_salah_sadio_ma",
        "fwd_survival_8goals",
        "auto_fwd_teammate_nick_pope_excluding_alexander_isak"
      ]
    },
    {
      "date": "2026-08-17",
      "path": "challenges/2026-08-17.js",
      "id": "daily-022-the-generated-mix",
      "number": 22,
      "title": "17 August 2026 · The Generated Mix",
      "difficulty": "Mixed",
      "formation": "4-4-2",
      "formationCounts": {
        "GK": 1,
        "DEF": 4,
        "MID": 4,
        "FWD": 2
      },
      "theme": "Generated Mix",
      "perfectScore": 2125,
      "promptIds": [
        "auto_gk_season_2019_20_points_40",
        "auto_def_career_clubs_3_points_60",
        "auto_def_bottom_assists_5",
        "auto_def_teammate_ayoze_perez_excluding_jonny_evans",
        "auto_def_teammate_tyrone_mings",
        "auto_mid_teammate_harry_maguire_points_80",
        "auto_mid_jurgen_klopp_minutes_1000_excluding_mohamed_salah",
        "auto_mid_teammate_tomas_soucek_excluding_jarrod_bowen",
        "auto_mid_career_seasons_10_points_70",
        "auto_fwd_season_2024_25_points_70_excluding_alexander_isak_chris_wood",
        "auto_fwd_promoted_goals_8"
      ]
    }
  ]
};
